version: "3.9"

services:
  api:
    build: .
    container_name: rag-server
    ports:
      - "8000:8000"
    env_file:
      - .env
    # depends_on:
    #   # - db
    volumes:
      - .:/app
    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

  test:
    build: .
    container_name: rag-test
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      pytest --cov=app tests/
    profiles:
      - testing

  # db:
  #   image: postgres:16
  #   container_name: fastapi-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: app_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
# volumes:
#   pgdata:
